### ISSUE TITLE
Error when using set_parameter and support for extra_parameters

### ISSUE THREAD

**Issue by bdiringer** [chef-partners/vmware-vra-gem#38]
I’ve been using knife-vrealize to provision machines through vRA, but I’m getting an error message when requesting a catalog item that has required parameters:

`knife vra server create 31ed3b5a-bfb7-4078-bcca-5a876ebb62ae --winrm-user dev\\ben.diringer --winrm-password **** --requested-for ben.diringer@****.com --vra-disable-ssl-verify --subtenant-id 5bd3f9c0-136e-4c28-b4cf-0a6f0a06b313 --lease-days 1 --image-os-type windows --bootstrap-protocol winrm --server-create-timeout 1000 --cpus 1 --memory 2048 -V --extra-param VirtualMachine.Network0.Name=string:DEV-ADMIN-1216_vDS --extra-param Extensibility.Workflows.RegisterNode.Properties.roles=string:build_node --extra-param VMware.VirtualCenter.Folder=string:Admin --extra-param Extensibility.Workflows.RegisterNode.Properties.environment=string:union
INFO: Using configuration from /Users/ben.diringer/projects/testing/.chef/knife.rb
ERROR: Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.`

I tried the same thing with the vra gem directly:

`>require 'openssl'
>require 'vra'
>vra = Vra::Client.new(username: 'ben.diringer', password: '****', tenant: 'mbodev', base_url: 'https://enso.****.com', verify_ssl: false)
>catalog_request = vra.catalog.request('31ed3b5a-bfb7-4078-bcca-5a876ebb62ae', cpus: 1, memory: 2048, requested_for: 'ben.diringer@****.com', lease_days: 1)
>catalog_request.subtenant_id = '5bd3f9c0-136e-4c28-b4cf-0a6f0a06b313'
>catalog_request.set_parameter('VirtualMachine.Network0.Name', 'string', 'DEV-ADMIN-1216_vDS')
>catalog_request.set_parameter('Extensibility.Workflows.RegisterNode.Properties.roles', 'string', 'build_node')
>catalog_request.set_parameter('VMware.VirtualCenter.Folder', 'string', 'Admin')
>catalog_request.set_parameter('Extensibility.Workflows.RegisterNode.Properties.environment', 'string', 'union')
>request = catalog_request.submit
Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.
    from /Users/ben.diringer/.rvm/gems/ruby-2.2.6/gems/vmware-vra-2.0.0/lib/vra/catalog_request.rb:104:in `rescue in submit'
    from /Users/ben.diringer/.rvm/gems/ruby-2.2.6/gems/vmware-vra-2.0.0/lib/vra/catalog_request.rb:100:in `submit'
    from (irb):14
    from /Users/ben.diringer/.rvm/rubies/ruby-2.2.6/bin/irb:11:in `<main>'`

Using vmare-vra-gem 2.0 and vRA 7.2.

**Comment by jjasghar** [comment]
Can you try putting the `--extra-param` in `'` to see if that fixes it? Then after that can you try using `2.3.1` of ruby? It seems you are using `2.2.6`.

**Comment by bdiringer** [comment]
Hi JJ,

Still getting the same error.  Tried adding single quotes around --extra-param and also tried upgrading ruby to 2.3.1.

`ben.diringer@:~/projects/testing$ ruby --version`
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`
`ben.diringer@:~/projects/testing$ knife vra server create 1a70b60c-39d8-4705-8e96-25241c94b61e --winrm-user dev\\ben.diringer --winrm-password **** --requested-for ben.diringer@****.com --subtenant-id 5bd3f9c0-136e-4c28-b4cf-0a6f0a06b313 --lease-days 1 --image-os-type windows --bootstrap-protocol winrm --server-create-timeout 1000 --cpus 2 --memory 4096 -V --extra-param provider-VirtualMachine.Network0.Name=string:DEV-ADMIN-1216_vDS --extra-param provider-VMware.VirtualCenter.Folder=string:Admin`
`INFO: Using configuration from /Users/ben.diringer/projects/testing/.chef/knife.rb`
`ERROR: Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.`
`ben.diringer@:~/projects/testing$ knife vra server create 1a70b60c-39d8-4705-8e96-25241c94b61e --winrm-user dev\\ben.diringer --winrm-password **** --requested-for ben.diringer@****.com --subtenant-id 5bd3f9c0-136e-4c28-b4cf-0a6f0a06b313 --lease-days 1 --image-os-type windows --bootstrap-protocol winrm --server-create-timeout 1000 --cpus 2 --memory 4096 -V --extra-param 'provider-VirtualMachine.Network0.Name=string:DEV-ADMIN-1216_vDS' --extra-param 'provider-VMware.VirtualCenter.Folder=string:Admin'`
`INFO: Using configuration from /Users/ben.diringer/projects/testing/.chef/knife.rb`
`ERROR: Vra::Exception::RequestError: Unable to submit request: The data specified within the 
request is invalid., Composite Exception.`

`irb`
`2.2.6 :001 > require 'openssl'`
` => true `
`2.2.6 :002 > require 'vra'`
` => true `
`2.2.6 :003 > vra = Vra::Client.new(username: 'ben.diringer', password: '****', tenant: 'mbodev', base_url: 'https://enso.****.com', verify_ssl: false)`
` => #<Vra::Client:0x007f8025a50710 @base_url="https://enso.****.com", @username="ben.diringer", @password=********, @tenant="mbodev", @verify_ssl=false, @bearer_token=********, @page_size=20> `
`2.2.6 :004 > catalog_request = vra.catalog.request('1a70b60c-39d8-4705-8e96-25241c94b61e', cpus: 1, memory: 2048, requested_for: 'ben.diringer@****.com', lease_days: 1)`
` => #<Vra::CatalogRequest:0x007f802611d7c8 @client=#<Vra::Client:0x007f8025a50710 @base_url="https://enso.****.com", @username="ben.diringer", @password=********, @tenant="mbodev", @verify_ssl=false, @bearer_token=********, @page_size=20>, @catalog_id="1a70b60c-39d8-4705-8e96-25241c94b61e", @cpus=1, @memory=2048, @requested_for="ben.diringer@****.com", @lease_days=1, @notes=nil, @subtenant_id=nil, @additional_params=#<Vra::RequestParameters:0x007f802611d7a0 @entries={}>, @catalog_item=#<Vra::CatalogItem:0x007f802611d728 @client=#<Vra::Client:0x007f8025a50710 @base_url="https://enso.****.com", @username="ben.diringer", @password=********, @tenant="mbodev", @verify_ssl=false, @bearer_token=********, @page_size=20>, @id="1a70b60c-39d8-4705-8e96-25241c94b61e", @catalog_item_data={"callbacks"=>nil, "catalogItemTypeRef"=>{"id"=>"com.vmware.csp.component.cafe.composition.blueprint", "label"=>"Composite Blueprint"}, "dateCreated"=>"2017-01-19T20:30:11.475Z", "description"=>"RTP, OS - W, CPU - 2 Core, RAM - 4GB, Disk - 60GB", "forms"=>{"itemDetails"=>{"type"=>"external", "formId"=>"composition.catalog.item.details"}, "catalogRequestInfoHidden"=>true, "requestFormScale"=>"BIG", "requestSubmission"=>{"type"=>"extension", "extensionId"=>"com.vmware.vcac.core.design.blueprints.requestForm", "extensionPointId"=>nil}, "requestDetails"=>{"type"=>"extension", "extensionId"=>"com.vmware.vcac.core.design.blueprints.requestDetailsForm", "extensionPointId"=>nil}}, "iconId"=>"composition.blueprint.png", "id"=>"1a70b60c-39d8-4705-8e96-25241c94b61e", "isNoteworthy"=>false, "lastUpdatedDate"=>"2017-01-19T20:30:32.673Z", "name"=>"ben-test-vm-withfields", "organization"=>{"tenantRef"=>"mbodev", "tenantLabel"=>"MBO-Dev", "subtenantRef"=>nil, "subtenantLabel"=>nil}, "outputResourceTypeRef"=>{"id"=>"composition.resource.type.deployment", "label"=>"Deployment"}, "providerBinding"=>{"bindingId"=>"mbodev!::!bentestvmwithfields", "providerRef"=>{"id"=>"92f3b64d-fb90-46b7-87b8-081addf68795", "label"=>"Blueprint Service"}}, "serviceRef"=>{"id"=>"5a1f232e-642f-4fa1-96d9-5934ec4cc160", "label"=>"Eng - Test Blueprints"}, "status"=>"PUBLISHED", "statusName"=>"Published", "quota"=>0, "version"=>1, "requestable"=>true}>> `
`2.2.6 :005 > catalog_request.subtenant_id = '5bd3f9c0-136e-4c28-b4cf-0a6f0a06b313'`
` => "5bd3f9c0-136e-4c28-b4cf-0a6f0a06b313" `
`2.2.6 :006 > catalog_request.set_parameter('VirtualMachine.Network0.Name', 'string', 'DEV-ADMIN-1216_vDS')`
` => #<Vra::RequestParameter:0x007f8025a320f8 @key="VirtualMachine.Network0.Name", @type="string", @value="DEV-ADMIN-1216_vDS"> `
`2.2.6 :007 > catalog_request.set_parameter('VMware.VirtualCenter.Folder', 'string', 'Admin')
 => #<Vra::RequestParameter:0x007f8025a11448 @key="VMware.VirtualCenter.Folder", @type="string", @value="Admin"> `
`2.2.6 :008 > request = catalog_request.submit`
`Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.`
`	from /Users/ben.diringer/.rvm/gems/ruby-2.2.6/gems/vmware-vra-2.0.0/lib/vra/catalog_request.rb:104:in 'rescue in submit'`
`	from /Users/ben.diringer/.rvm/gems/ruby-2.2.6/gems/vmware-vra-2.0.0/lib/vra/catalog_request.rb:100:in 'submit'`
`	from (irb):8`
`	from /Users/ben.diringer/.rvm/rubies/ruby-2.2.6/bin/irb:11:in '<main>'`

**Comment by bdiringer** [comment]
I think I figured out the problem.  The parameters should be wrapped inside a "complex" parameter.
Might need to extend request_parameters.rb to allow for complex parameters.

Here's the post body of a working call (grabbed browser request with a web debugging proxy):

```
{
    "@type": "CatalogItemRequest",
    "catalogItemRef": {
        "id": "1a70b60c-39d8-4705-8e96-25241c94b61e"
    },
    "organization": {
        "tenantRef": "mbodev",
        "subtenantRef": "bb8cfb0a-339c-428a-92f7-e602ac5f902c"
    },
    "requestedFor": "ben.diringer@****.com",
    "state": "SUBMITTED",
    "requestNumber": 0,
    "requestData": {
        "entries": [
            {
                "key": "requestedFor",
                "value": {
                    "type": "string",
                    "value": "ben.diringer@****.com"
                }
            },
            {
                "key": "provider-w-mbo.2xsmall",
                "value": {
                    "type": "complex",
                    "componentTypeId": "com.vmware.csp.iaas.blueprint.service",
                    "classId": "Blueprint.Node",
                    "typeFilter": "bentestvmwithfields*w-mbo.2xsmall",
                    "values": {
                        "entries": [
                            {
                                "key": "VirtualMachine.Network0.Name",
                                "value": {
                                    "type": "string",
                                    "value": "DEV-ADMIN-1216_vDS"
                                }
                            },
                            {
                                "key": "VMware.VirtualCenter.Folder",
                                "value": {
                                    "type": "string",
                                    "value": "Admin"
                                }
                            }
                        ]
                    }
                }
            },
            {
                "key": "description"
            },
            {
                "key": "reasons"
            }
        ]
    }
}
```

**Comment by jjasghar** [comment]
Basically we need to figure out how to add `extra_params` to this: https://github.com/chef-partners/vmware-vra-gem/blob/master/lib/vra/catalog_request.rb#L79-L85

**Comment by jjasghar** [comment]
http://www.virtualvcp.com/vmware-vrealize-automation-vcac/220-vro-vra7-catalog-item-provisioning-requests-json-and-referencing-properties

**Comment by jjasghar** [comment]
https://github.com/chef-partners/kitchen-vra/issues/20

**Comment by cstewart87** [comment]
Troubleshooting this now in my sandbox vra 7.1 environment.  Will continue to do some testing rest of this week, and might have a potential solution in 1-2 days.  Believe this may be a result of slightly different data structures for properties.

**Comment by jjasghar** [comment]
Awesome @cstewart87 I'm here when you need me.

**Comment by cstewart87** [comment]
So, starting to look like this might be a bigger effort than a simple 2-3 line change :(.  However, I still think I know the issue.

Appears this gem is using the response from the API for `entitledCatalogItems` (`/catalog-service/api/consumer/entitledCatalogItems`) to add the extra parameters to then sending a POST request with all of the relevant information to provision the blueprint.

I was able to confirm that using the `requests/template` API instead (`/catalog-service/api/consumer/entitledCatalogItems/#{id}/requests/template`) and updating with required settings, including custom/extra params, properly provisions a blueprint with all custom/extra params passed through successfully.

Some sample requests using the APIs directly are available in the vRA 7.2 docs [here](https://pubs.vmware.com/vrealize-automation-72/index.jsp?topic=%2Fcom.vmware.vra.programming.doc%2FGUID-C353A9E9-B2B6-43D0-89A5-B59B11522AC8.html), and I confirmed requesting a blueprint in this fashion works on 7.1 as well.

I say this looks like a bigger effort because the `Vra::CatalogItem` class likely needs to be updated to support this new template response, or a new `Vra::CatalogItemTemplate` (or similar) class needs to be created for supporting vRA 7.x.

Open to suggestions from anyone who's been helping to create/maintain this gem on a simpler solution.  Until then, going back to the drawing board myself to determine a proper solution :)

**Comment by cstewart87** [comment]
@jjasghar - FYI, I'm likely being pulled away from this for now, so I won't be able to put much more time into a solution/PR myself.  Hopefully what I've provided helps you all continue with a solution though.  Let me know if you have any questions.

**Comment by bdiringer** [comment]
Hi,

I'm still having this issue in 2.1.1.  I could be doing something wrong, but I've tried passing parameters in various ways:

```
ben.diringer@:~/projects/testing$ knife vra server create 53787c09-4bd3-45fa-a0fc-85ae90476d4e --winrm-user dev\\ben.diringer --winrm-password **** --requested-for ben.diringer@****.com --vra-disable-ssl-verify --subtenant-id bb8cfb0a-339c-428a-92f7-e602ac5f902c --lease-days 1 --image-os-type windows --bootstrap-protocol winrm --server-create-timeout 1000 --cpus 2 --memory 4096 -V --extra-param VirtualMachine.Network0.Name=string:'DEV-ADMIN-1216_vDS' --extra-param VMware.VirtualCenter.Folder=string:'Admin'
INFO: Using configuration from /Users/ben.diringer/projects/testing/.chef/knife.rb
ERROR: Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.
ben.diringer@:~/projects/testing$ knife vra server create 53787c09-4bd3-45fa-a0fc-85ae90476d4e --winrm-user dev\\ben.diringer --winrm-password **** --requested-for ben.diringer@****.com --vra-disable-ssl-verify --subtenant-id bb8cfb0a-339c-428a-92f7-e602ac5f902c --lease-days 1 --image-os-type windows --bootstrap-protocol winrm --server-create-timeout 1000 --cpus 2 --memory 4096 -V --extra-param VirtualMachine.Network0.Name=string:DEV-ADMIN-1216_vDS --extra-param VMware.VirtualCenter.Folder=string:Admin
INFO: Using configuration from /Users/ben.diringer/projects/testing/.chef/knife.rb
ERROR: Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.
ben.diringer@:~/projects/testing$ knife vra server create 53787c09-4bd3-45fa-a0fc-85ae90476d4e --winrm-user dev\\ben.diringer --winrm-password **** --requested-for ben.diringer@****.com --vra-disable-ssl-verify --subtenant-id bb8cfb0a-339c-428a-92f7-e602ac5f902c --lease-days 1 --image-os-type windows --bootstrap-protocol winrm --server-create-timeout 1000 --cpus 2 --memory 4096 -V --extra-param provider-VirtualMachine.Network0.Name=string:DEV-ADMIN-1216_vDS --extra-param provider-VMware.VirtualCenter.Folder=string:Admin
INFO: Using configuration from /Users/ben.diringer/projects/testing/.chef/knife.rb
ERROR: Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.
ben.diringer@:~/projects/testing$ knife vra server create 53787c09-4bd3-45fa-a0fc-85ae90476d4e --winrm-user dev\\ben.diringer --winrm-password **** --requested-for ben.diringer@****.com --vra-disable-ssl-verify --subtenant-id bb8cfb0a-339c-428a-92f7-e602ac5f902c --lease-days 1 --image-os-type windows --bootstrap-protocol winrm --server-create-timeout 1000 --cpus 2 --memory 4096 -V --extra-param 'provider-VirtualMachine.Network0.Name=string:DEV-ADMIN-1216_vDS' --extra-param 'provider-VMware.VirtualCenter.Folder=string:Admin'
INFO: Using configuration from /Users/ben.diringer/projects/testing/.chef/knife.rb
ERROR: Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.
ben.diringer@:~/projects/testing$ knife vra server create 53787c09-4bd3-45fa-a0fc-85ae90476d4e --winrm-user dev\\ben.diringer --winrm-password **** --requested-for ben.diringer@****.com --vra-disable-ssl-verify --subtenant-id bb8cfb0a-339c-428a-92f7-e602ac5f902c --lease-days 1 --image-os-type windows --bootstrap-protocol winrm --server-create-timeout 1000 --cpus 2 --memory 4096 -V --extra-param 'VirtualMachine.Network0.Name=string:DEV-ADMIN-1216_vDS' --extra-param 'VMware.VirtualCenter.Folder=string:Admin'
INFO: Using configuration from /Users/ben.diringer/projects/testing/.chef/knife.rb
ERROR: Vra::Exception::RequestError: Unable to submit request: The data specified within the request is invalid., Composite Exception.
```

Let me know what other debugging data I can gather.

Thanks,

-Ben

**Comment by vinyar** [comment]
linking: https://github.com/chef-partners/knife-vrealize/issues/20

**Comment by nsdavidson** [comment]
Confirmed with @bdiringer this is fixed in 2.1.3

**Comment by maheshrajannan** [comment]
I am using the versions below but still facing the same error. Which one should i upgrade ?

I am on a mac 10.10.5(yosemite).

MLRW086499:.ssh mrajann$ chef --version
Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0
MLRW086499:.ssh mrajann$ 

MLRW086499:hello_world mrajann$ kitchen create
-----> Starting Kitchen (v1.16.0)
WARN: Unresolved specs during Gem::Specification.reset:
      winrm-fs (~> 1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
-----> Creating <default-ChefDK>...
       Building vRA catalog request...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Unable to submit request: The data specified within the request is invalid., Composite Exception.] on default-ChefDK
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

MLRW086499:hello_world mrajann$ 


E, [2017-11-11T14:28:34.630866 #10608] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-11-11T14:28:34.630893 #10608] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Unable to submit request: The data specified within the request is invalid., Composite Exception.] on default-ChefDK
E, [2017-11-11T14:28:34.630918 #10608] ERROR -- Kitchen: ----------------------
E, [2017-11-11T14:28:34.630940 #10608] ERROR -- Kitchen: ------Backtrace-------
E, [2017-11-11T14:28:34.630957 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-11-11T14:28:34.630970 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
E, [2017-11-11T14:28:34.630982 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
E, [2017-11-11T14:28:34.630994 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-11-11T14:28:34.631006 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
E, [2017-11-11T14:28:34.631017 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-11-11T14:28:34.631029 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
E, [2017-11-11T14:28:34.631041 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-11-11T14:28:34.631053 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-11-11T14:28:34.631065 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-11-11T14:28:34.631076 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-11-11T14:28:34.631088 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-11-11T14:28:34.631105 #10608] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'

**Comment by jjasghar** [comment]
What version of vRA are you connecting to?
